name: BardServerProject
main: bard.liyang.bardserverproject.BardServerProject
version: 1.0
api-version: 1.16
commands:
 removeusers:
  description: Removes user yaml data for weapon exclusivity
  usage: /<command>
 armor:
  description: adds netherite armor
  usage: /<command>
 general:
  description: spawns general
  usage: /<command>
 mongol:
  description: spawns mongol
  usage: /<command>
 hydra:
  description: spawns mongol
  usage: /<command>